
export const locations = ['AAKRITI ECOCITY, BHOPAL', 'ABBAS NAGAR, BHOPAL', 'AIRPORT AREA, BHOPAL', 'ANAND NAGAR, BHOPAL', 'ARERA COLONY, BHOPAL', 'ASHOKA GARDEN , BHOPAL', 'ASHOKA GARDEN, BHOPAL', 'AWADHPURI, BHOPAL', 'AYODHYA NAGAR EXTENTION, BHOPAL', 'AYODHYA NAGAR, BHOPAL', 'BAGH MUNGALIYA, BHOPAL', 'BHANPURA, BHOPAL', 'BHEL , BHOPAL', 'CHUNABHATTI, BHOPAL', 'DANISH SQUARE, BHOPAL', 'ECO GREEN CITY, BHOPAL', 'GOVINDPURA, BHOPAL', 'GULMOHAR COLONY, BHOPAL', 'INDRAPURI, BHOPAL', 'ISRO COLONY, BHOPAL', 'JHANGIRABAD, BHOPAL', 'KAROD KALAN, BHOPAL', 'KATARA HILLS, BHOPAL', 'KOH E FIZA, BHOPAL', 'KOKTA, BHOPAL', 'KOLAR ROAD, BHOPAL', 'LAL GHATI CHOURAHA, BHOPAL', 'MISROD, BHOPAL', 'MP NAGAR, BHOPAL', 'NARILA SHANKARI, BHOPAL', 'NEHRU NAGAR, BHOPAL', 'NEW MINAL RESIDENCY, BHOPAL', 'OLD MINAL RESIDENCY, BHOPAL', 'PANCHVATI, BHOPAL', 'PATEL NAGAR, BHOPAL', 'PIPLANI, BHOPAL', 'RAJEEV NAGAR, BHOPAL', 'RATNAGIRI BDA COLONY, BHOPAL', 'ROHIT NAGAR, BHOPAL', 'SAKET NAGAR, BHOPAL', 'SANJEEV NAGAR, BHOPAL', 'SEMRA, BHOPAL', 'SHAHPURA, BHOPAL', 'SHIVAJI NAGAR, BHOPAL', 'TT NAGAR, BHOPAL']

export const BHK = [
    {
        name : "1BHK",
        value : 1
    },
    {
        name : "2BHK",
        value : 2
    },
    {
        name : "3BHK",
        value : 3
    },

]